### PR TITLE
Newsletter done

### LINKED ISSUE #42: Newsletter backend
Newsletter backend need to be done
1. Form on submit => response in spreadsheet => automatic email

### PR DESCRIPTION
**Pull request by ayan-biswas0412**
Need to do some more modifications in the newsletter section

### CODE REVIEW

**Comment by ayan-biswas0412** [comment]
Newsletter is done if anybody subscribes that he/she gets an email in inbox pull and check this and you will find corresponding spreadsheet under the contacts.ieeeju email 

FYI @shreyab1111 @biparnakroy @iamtamodip if all thing fare fine merge this

**Comment by biparnakroy** [comment]
everything is fine but on submitting 
image
this is coming up 
eta shortey parish kina dekh

**Comment by ayan-biswas0412** [comment]
> everything is fine but on submitting
> image
> this is coming up
> eta shortey parish kina dekh

@biparnakroy sokale dekhchi ekhn suye porechi

**Comment by biparnakroy** [comment]
achha cool!!

**Pull request merged**
